development:
  adapter: mysql
  encoding: utf8
  database: greenalytics
  username: greenaly_admin
  password: CpwPA4nFv9mV
  host: 70.32.99.240
 
production:
  adapter: mysql
  encoding: utf8
  database: greenalytics
  username: greenaly_admin
  password: CpwPA4nFv9mV
  host: 70.32.99.240
