development:
  adapter: mysql
  encoding: utf8
  database: greenalytics
  username: root
  password: rip2maQ8
  host: verdemedia.org
 
production:
  adapter: mysql
  encoding: utf8
  database: greenalytics
  username: root
  password: rip2maQ8
  host: verdemedia.org
