development:
  adapter: mysql
  encoding: utf8
  database: greenalytics
  username: greenaly_admin
  password: CpwPA4nFv9mV
  host: 79.99.1.46
 
production:
  adapter: mysql
  encoding: utf8
  database: greenalytics
  username: greenaly_admin
  password: CpwPA4nFv9mV
  host: 79.99.1.46
