development:
  adapter: mysql
  encoding: utf8
  database: greenalytics
  username: greenaly_admin
  password: CpwPA4nFv9mV
  host: verdemedia.org
 
production:
  adapter: mysql
  encoding: utf8
  database: greenalytics
  username: greenaly_admin
  password: CpwPA4nFv9mV
  host: verdemedia.org
